### ISSUE TITLE
CSS class naming

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#11]
It is quite an art to name CSS classes so that their specifity is not so broad that you end up styling elements unintentionally. I think from looking at your code you might use [BEM](http://getbem.com/naming/) at your shop. 

I can't argue with that but it can be overkill for small projects. Also, frameworks like Angular encourage you to use lots of small CSS and HTML files, rather than one giant one, with each CSS+HTML isolated from the other. So the need for absolute unambiguity in one huge global namespace goes away.

Not only that, `<p class="letterForm letterForm--phraseOne">` looks 'noisy' and, in all that text, it can be difficult to spot the important difference between `phraseOne` and `phraseTwo`.

I would recommend using simple 'inside' selectors wherever possible. So you could code this:

```css
.grid p {
    align-items: center;
    background-color: #EEEEEE;
    display: flex;
    font-size: 1rem;
    height: 100%;
    justify-content: center;
    margin: 0;
    padding: 0;
    text-align: center;
    width: 100%;
}

.grid p .phraseOne {
    color: #999999;
}


.grid p .phraseTwo {
    color: #666666;
}
```

Now your HTML looks simpler:

```html
<div class="grid">
  ...
  <p class="phraseOne">...</p>
  ...
  <p class="phraseTwo">...</p>
  ...
</div>
```
